# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Bourbeau
author: James Bourbeau
email: jbourbeau@wisc.edu
description: I'm a physics Ph.D. graduate student and data analyst with an interest in machine learning
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jamesbourbeau.com" # the base hostname & protocol for your site
twitter_username: bourbeaujames
github_username:  jrbourbeau
encoding: "utf-8"

# Build settings
markdown: kramdown
