baseurl = "https://jrbourbeau.github.io/"
title = "James Bourbeau"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-130389564-1"

[permalinks]
  posts = "/:section/:year/:title/"

[params]
    author = "James Bourbeau"
    description = "James Bourbeau's personal website"
    keywords = "blog,developer,personal"
    info = "Software Engineer and open-source community member"
    avatarurl = "images/image.jpg"
    
    favicon_16 = "images/favicon-16x16.png"
    favicon_32 = "images/favicon-32x32.png"

    footercontent = " "

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true

    rtl = false

    # Use inverted colors
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = ["css/custom.css"]
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/jrbourbeau/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/__jrbourbeau__/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/jrbourbeau/"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Résumé"
            weight = 5
            url = "resume/"
